"""Mechanical quality gates (§6) — pure rules over a parsed Draft.

These catch the cheap, mechanical failures (missing SEO, too short, generic-AI
phrasing) before a human is ever asked to approve a draft. The LLM-judgment gates
(fact-check, true voice, real human-read) stay with the editor skill, not here.
"""
from __future__ import annotations

import re

from .article import Draft, GateResult

# §6 Human-read / §5 voice guide: phrases that betray generic-AI prose. Hard-fail.
AI_TELLS = [
    "di era digital",
    "di era modern",
    "sumber daya yang sangat berharga",
    "menjadi salah satu aktivitas sebagian orang",
    "hadir sebagai solusi",
    "memungkinkan anda untuk",
    "perlu diingat bahwa",
    "tidak dapat dipungkiri",
    "sangat penting untuk",
    "dalam rangka",
    "sebagai penutup",
    "demikianlah",
    "dengan demikian",
    "generated by ai",
    "created by ai",
    # --- Data-driven additions (2026-06-22, journal failure analysis) ---
    "generate by ai",              # variant: typo case dari blog lama
    "ai-generated",                # variant: hyphenated form
    "dalam artikel ini",           # AI meta-commentary (ditemukan di 1 draft)
    "panduan lengkap",             # generic descriptor (ditemukan di 2 drafts)
]

# §6 completeness floor (mechanical; real quality is the editor/human's job).
MIN_WORDS = 600
TITLE_PLACEHOLDER = "[JUDUL ARTIKEL]"

_COMMENT_RE = re.compile(r"<!--.*?-->", re.DOTALL)
_H1_RE = re.compile(r"^#\s+\S", re.MULTILINE)
# §: every article needs a featured image — a real markdown image OR an
# `<!-- img: ... -->` placeholder the imagery/publish step will fill.
_IMAGE_RE = re.compile(r"!\[[^\]]*\]\([^)]+\)|<!--\s*img", re.IGNORECASE)
_WORD_RE = re.compile(r"\w+")
_ANDA_RE = re.compile(r"\bAnda\b")

# §6 pre-publish / pre-gate: unresolved markers that must never reach live.
# Catches TODO/FIXME/HACK/XXX with ( or : form, plus [REDACTED].
_UNRESOLVED_RE = re.compile(
    r"(?:TODO|FIXME|HACK|XXX)\s*[( :]|"  # TODO(  FIXME(  HACK(  TODO:  FIXME:
    r"\[REDACTED\]",                       # [REDACTED]
    re.IGNORECASE,
)


def evaluate(draft: Draft, check_links: bool = True) -> GateResult:
    """Run all mechanical gates against a draft, returning failures + warnings.

    Args:
        check_links: If True, run link validation (HTTP checks). Set False for
                     fast offline runs (domain blocklist still checked).
    """
    result = GateResult()
    seo = draft.seo
    body = draft.body

    # Completeness
    if TITLE_PLACEHOLDER in draft.raw or not _H1_RE.search(body):
        result.failures.append("judul masih placeholder / belum ada H1")
    if not seo.get("title"):
        result.failures.append("seo.title kosong")
    if not seo.get("meta_description"):
        result.failures.append("seo.meta_description kosong")
    if not seo.get("slug"):
        result.failures.append("seo.slug kosong")
    if not seo.get("keywords"):
        result.failures.append("seo.keywords kosong")

    # Length floor
    words = len(_WORD_RE.findall(body))
    if words < MIN_WORDS:
        result.failures.append(f"terlalu pendek: {words} kata (min {MIN_WORDS})")

    # Featured image required (placeholder or real image)
    if not _IMAGE_RE.search(body):
        result.failures.append("belum ada gambar/featured image (butuh ![](...) atau <!-- img -->)")

    # AI-tells (hard) — strip HTML comments so template hints don't trip it
    visible = _COMMENT_RE.sub("", body.lower())
    hit = [p for p in AI_TELLS if p in visible]
    if hit:
        result.failures.append(
            "frasa AI/generic terdeteksi: " + ", ".join(f'"{p}"' for p in hit)
        )

    # §6 Unresolved markers — TODO/FIXME/HACK/XXX/REDACTED must never reach live
    visible_for_markers = _COMMENT_RE.sub("", body)   # strip HTML comments, keep case
    marker_hits = _UNRESOLVED_RE.findall(visible_for_markers)
    if marker_hits:
        result.failures.append(
            "marker unresolved: " + ", ".join(f'"{m}"' for m in marker_hits)
        )

    # Voice nudges (warn, not fail)
    if _ANDA_RE.search(body):
        result.warnings.append('pakai "Anda" — voice guide minta "kamu"/"sobat"')
    title_blob = (seo.get("title", "") + draft.idea_id).lower()
    if "```" not in body and "tutorial" in title_blob:
        result.warnings.append("tutorial tanpa code block (§7)")

    # Em-dash density — excessive em-dashes are a reliable AI signal.
    # editor-checklist: max 1 per 500 words. Warn if exceeded.
    em_dash_count = body.count("—")
    if em_dash_count > 0 and words > 0:
        per_500 = em_dash_count / words * 500
        if per_500 > 2.0:  # hard warn: >2 per 500 words
            result.warnings.append(
                f"em dash (—) berlebihan: {em_dash_count}x "
                f"({per_500:.1f} per 500 kata) — AI formatting trace"
            )

    # §8 Link validation — hoax/dead link detection
    from .link_validator import validate_links
    link_result = validate_links(body, check_http=check_links)
    result.failures.extend(link_result.failures)
    result.warnings.extend(link_result.warnings)

    return result
