#!/usr/bin/env python3
"""
Blog Analytics Addon — Setup Script

Interactive setup untuk GA4, GSC, GTM integration.

Usage:
    python3 analytics-addon/scripts/setup_analytics.py
"""

import os
import sys
from pathlib import Path
from datetime import datetime

# ============================================================
# ANALYTICS COMPONENTS
# ============================================================

ANALYTICS_COMPONENTS = [
    {
        "id": "ga4",
        "name": "Google Analytics 4",
        "description": "Track pageviews, events, conversions",
        "required": True,
        "env_keys": ["GA4_PROPERTY_ID", "GA4_CREDENTIALS_PATH"],
        "docs": "docs/GA4_SETUP_TUTORIAL.md",
    },
    {
        "id": "gsc",
        "name": "Google Search Console",
        "description": "Monitor search performance, keywords",
        "required": False,
        "env_keys": ["GSC_PROPERTY_URL", "GSC_CREDENTIALS_PATH"],
        "docs": None,
    },
    {
        "id": "gtm",
        "name": "Google Tag Manager",
        "description": "Manage tags, triggers, variables",
        "required": False,
        "env_keys": ["GTM_CONTAINER_ID"],
        "docs": None,
    },
]

# ============================================================
# INTERACTIVE WIZARD
# ============================================================

def get_input(prompt, default="", required=True):
    """Get user input with default value."""
    while True:
        value = input(f"{prompt} [{default}]: ").strip()
        if not value and default:
            return default
        if not value and required:
            print("  ⚠️  Required field. Please enter a value.")
            continue
        return value

def setup_ga4():
    """Setup Google Analytics 4."""
    print()
    print("📊 GOOGLE ANALYTICS 4")
    print("-" * 40)
    print("Setup GA4 untuk track pageviews dan events.")
    print()
    print("Steps:")
    print("1. Buat Google Cloud Project")
    print("2. Enable GA4 Data API")
    print("3. Buat Service Account")
    print("4. Download credentials.json")
    print()
    
    property_id = get_input("GA4 Property ID (angka)")
    credentials_path = get_input("Path ke credentials.json", "credentials.json", required=False)
    
    return {
        "GA4_PROPERTY_ID": property_id,
        "GA4_CREDENTIALS_PATH": credentials_path,
    }

def setup_gsc():
    """Setup Google Search Console."""
    print()
    print("📈 GOOGLE SEARCH CONSOLE")
    print("-" * 40)
    print("Setup GSC untuk monitor search performance.")
    print()
    
    use_gsc = input("  Pakai GSC? (y/n) [n]: ").strip().lower()
    if use_gsc != 'y':
        return {}
    
    property_url = get_input("Website URL (e.g., https://yourdomain.com)")
    credentials_path = get_input("Path ke credentials.json", "credentials.json", required=False)
    
    return {
        "GSC_PROPERTY_URL": property_url,
        "GSC_CREDENTIALS_PATH": credentials_path,
    }

def setup_gtm():
    """Setup Google Tag Manager."""
    print()
    print("🏷️  GOOGLE TAG MANAGER")
    print("-" * 40)
    print("Setup GTM untuk manage tags dan triggers.")
    print()
    
    use_gtm = input("  Pakai GTM? (y/n) [n]: ").strip().lower()
    if use_gtm != 'y':
        return {}
    
    container_id = get_input("GTM Container ID (GTM-XXXXXXX)")
    
    return {
        "GTM_CONTAINER_ID": container_id,
    }

# ============================================================
# CONFIG GENERATOR
# ============================================================

def generate_analytics_config(env_vars, output_path="config/analytics.yaml"):
    """Generate analytics config file."""
    
    template = f"""# Analytics Configuration — generated by setup script
# Generated: {datetime.now().isoformat()}

ga4:
  property_id: "{env_vars.get('GA4_PROPERTY_ID', '')}"
  credentials_path: "{env_vars.get('GA4_CREDENTIALS_PATH', 'credentials.json')}"

gsc:
  property_url: "{env_vars.get('GSC_PROPERTY_URL', '')}"
  credentials_path: "{env_vars.get('GSC_CREDENTIALS_PATH', 'credentials.json')}"

gtm:
  container_id: "{env_vars.get('GTM_CONTAINER_ID', '')}"
"""
    
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    Path(output_path).write_text(template)
    print(f"  ✅ {output_path}")

def generate_env_additions(env_vars, output_path=".env.analytics"):
    """Generate .env additions for analytics."""
    
    template = f"""# Analytics Environment Variables — generated by setup script
# Generated: {datetime.now().isoformat()}
# Add these to your main .env file

# === GOOGLE ANALYTICS 4 ===
GA4_PROPERTY_ID="{env_vars.get('GA4_PROPERTY_ID', '')}"
GA4_CREDENTIALS_PATH="{env_vars.get('GA4_CREDENTIALS_PATH', 'credentials.json')}"

# === GOOGLE SEARCH CONSOLE ===
GSC_PROPERTY_URL="{env_vars.get('GSC_PROPERTY_URL', '')}"
GSC_CREDENTIALS_PATH="{env_vars.get('GSC_CREDENTIALS_PATH', 'credentials.json')}"

# === GOOGLE TAG MANAGER ===
GTM_CONTAINER_ID="{env_vars.get('GTM_CONTAINER_ID', '')}"
"""
    
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    Path(output_path).write_text(template)
    print(f"  ✅ {output_path}")

# ============================================================
# MAIN
# ============================================================

def main():
    """Main entry point."""
    
    print("=" * 60)
    print("  Blog Analytics Addon — Setup Script")
    print("=" * 60)
    print()
    print("Setup analytics integration untuk Blog Lifecycle Pro.")
    print()
    
    all_env_vars = {}
    
    # GA4 (required)
    all_env_vars.update(setup_ga4())
    
    # GSC (optional)
    all_env_vars.update(setup_gsc())
    
    # GTM (optional)
    all_env_vars.update(setup_gtm())
    
    # Generate config files
    print()
    print("=" * 60)
    print("  Generating configuration files...")
    print("=" * 60)
    print()
    
    generate_analytics_config(all_env_vars)
    generate_env_additions(all_env_vars)
    
    # Generate summary
    print()
    print("=" * 60)
    print("  ✅ Analytics Setup Complete!")
    print("=" * 60)
    print()
    print("📋 NEXT STEPS:")
    print()
    print("1. Copy .env.analytics ke .env:")
    print("   cat .env.analytics >> .env")
    print()
    print("2. Download credentials.json dari Google Cloud Console")
    print()
    print("3. Install GA4 snippet di blog:")
    print("   <!-- Google Analytics -->")
    print("   <script async src=\"https://www.googletagmanager.com/gtag/js?id=GA4_PROPERTY_ID\"></script>")
    print()
    print("4. Verify setup:")
    print("   python3 -c \"from analytics import GA4Tracker; print('GA4 OK')\"")
    print()
    print("📊 YOUR ANALYTICS:")
    print(f"   GA4 Property:  {all_env_vars.get('GA4_PROPERTY_ID', 'Not set')}")
    print(f"   GSC Property:  {all_env_vars.get('GSC_PROPERTY_URL', 'Not set')}")
    print(f"   GTM Container: {all_env_vars.get('GTM_CONTAINER_ID', 'Not set')}")
    print()

if __name__ == "__main__":
    main()
